import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { api } from "y/utils/api";

import { PageLayout } from "y/components/layout";
import Image from "next/image";
import LoadingSpinner from "y/components/loading";
import { PostView } from "y/components/postView";
import { generateSSGHelper } from "y/server/helpers/ssgHelper";

const ProfileFeed = (props: { username: string }) => {
  const { data, isLoading } = api.posts.getPostsByUserId.useQuery({
    userId: props.username,
  });

  if (isLoading) return <LoadingSpinner />;

  if (!data || data.length === 0) return <div>No posts</div>;

  return (
    <div className="flex flex-col">
      {data.map((fullPost) => (
        <PostView {...fullPost} key={fullPost.post.id} />
      ))}
    </div>
  );
};

const ProfilePage: NextPage<{ username: string }> = ({ username }) => {
  const { data } = api.profile.getUserByUsername.useQuery({
    username,
  });

  if (!data) return <div>404</div>;
  return (
    <>
      <Head>
        <title>{data.username}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <div className="relative flex h-48 items-center  bg-slate-600 p-4 align-middle">
          <Image
            src={data.profilePicture}
            alt={`${data.username ?? ""} profile picture`}
            width={104}
            height={104}
            className="absolute bottom-0 left-0 -mb-14 ml-4 rounded-full border-4  border-black"
          />
        </div>
        <div className="h-[52px]"></div>
        <div className="border-b border-slate-400 p-4 text-2xl font-bold">{`@${
          data.username ?? ""
        }`}</div>
        <div className="border-b border-slate-400 p-2 ">
          <ProfileFeed username={data.id} />
        </div>
      </PageLayout>
    </>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const ssg = generateSSGHelper();

  const slug = context.params?.slug;

  if (typeof slug !== "string") {
    throw new Error("Slug is not a string");
  }

  const username = slug.replace("@", "");

  await ssg.profile.getUserByUsername.prefetch({ username });

  return {
    props: {
      trpcState: ssg.dehydrate(),
      username,
    },
  };
};

export const getStaticPaths = () => {
  return { paths: [], fallback: "blocking" };
};

export default ProfilePage;
